/*
 * This file is generated by jOOQ.
*/
package db.tables.records;


import db.tables.Status;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusRecord extends UpdatableRecordImpl<StatusRecord> {

    private static final long serialVersionUID = -251030871;

    /**
     * Setter for <code>tweetsenser.status.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>tweetsenser.status.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>tweetsenser.status.tweet_id</code>.
     */
    public void setTweetId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>tweetsenser.status.tweet_id</code>.
     */
    public Integer getTweetId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>tweetsenser.status.product</code>.
     */
    public void setProduct(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>tweetsenser.status.product</code>.
     */
    public String getProduct() {
        return (String) get(2);
    }

    /**
     * Setter for <code>tweetsenser.status.sub_product</code>.
     */
    public void setSubProduct(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>tweetsenser.status.sub_product</code>.
     */
    public String getSubProduct() {
        return (String) get(3);
    }

    /**
     * Setter for <code>tweetsenser.status.tweet_date</code>.
     */
    public void setTweetDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>tweetsenser.status.tweet_date</code>.
     */
    public Timestamp getTweetDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>tweetsenser.status.tweetmsg</code>.
     */
    public void setTweetmsg(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>tweetsenser.status.tweetmsg</code>.
     */
    public String getTweetmsg() {
        return (String) get(5);
    }

    /**
     * Setter for <code>tweetsenser.status.tweetsource</code>.
     */
    public void setTweetsource(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>tweetsenser.status.tweetsource</code>.
     */
    public String getTweetsource() {
        return (String) get(6);
    }

    /**
     * Setter for <code>tweetsenser.status.is_truncated</code>.
     */
    public void setIsTruncated(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>tweetsenser.status.is_truncated</code>.
     */
    public Byte getIsTruncated() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>tweetsenser.status.in_reply_to_status_id</code>.
     */
    public void setInReplyToStatusId(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>tweetsenser.status.in_reply_to_status_id</code>.
     */
    public Integer getInReplyToStatusId() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>tweetsenser.status.in_reply_to_user_id</code>.
     */
    public void setInReplyToUserId(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>tweetsenser.status.in_reply_to_user_id</code>.
     */
    public Integer getInReplyToUserId() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>tweetsenser.status.is_favorited</code>.
     */
    public void setIsFavorited(Byte value) {
        set(10, value);
    }

    /**
     * Getter for <code>tweetsenser.status.is_favorited</code>.
     */
    public Byte getIsFavorited() {
        return (Byte) get(10);
    }

    /**
     * Setter for <code>tweetsenser.status.is_retweeted</code>.
     */
    public void setIsRetweeted(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>tweetsenser.status.is_retweeted</code>.
     */
    public Byte getIsRetweeted() {
        return (Byte) get(11);
    }

    /**
     * Setter for <code>tweetsenser.status.favorite_count</code>.
     */
    public void setFavoriteCount(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>tweetsenser.status.favorite_count</code>.
     */
    public Integer getFavoriteCount() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>tweetsenser.status.in_reply_to_screen_name</code>.
     */
    public void setInReplyToScreenName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>tweetsenser.status.in_reply_to_screen_name</code>.
     */
    public String getInReplyToScreenName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>tweetsenser.status.geo_location</code>.
     */
    public void setGeoLocation(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>tweetsenser.status.geo_location</code>.
     */
    public String getGeoLocation() {
        return (String) get(14);
    }

    /**
     * Setter for <code>tweetsenser.status.place</code>.
     */
    public void setPlace(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>tweetsenser.status.place</code>.
     */
    public String getPlace() {
        return (String) get(15);
    }

    /**
     * Setter for <code>tweetsenser.status.retweet_count</code>.
     */
    public void setRetweetCount(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>tweetsenser.status.retweet_count</code>.
     */
    public Integer getRetweetCount() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>tweetsenser.status.is_possibly_sensitive</code>.
     */
    public void setIsPossiblySensitive(Byte value) {
        set(17, value);
    }

    /**
     * Getter for <code>tweetsenser.status.is_possibly_sensitive</code>.
     */
    public Byte getIsPossiblySensitive() {
        return (Byte) get(17);
    }

    /**
     * Setter for <code>tweetsenser.status.iso_language_code</code>.
     */
    public void setIsoLanguageCode(Byte value) {
        set(18, value);
    }

    /**
     * Getter for <code>tweetsenser.status.iso_language_code</code>.
     */
    public Byte getIsoLanguageCode() {
        return (Byte) get(18);
    }

    /**
     * Setter for <code>tweetsenser.status.lang</code>.
     */
    public void setLang(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>tweetsenser.status.lang</code>.
     */
    public String getLang() {
        return (String) get(19);
    }

    /**
     * Setter for <code>tweetsenser.status.retweeted_status</code>.
     */
    public void setRetweetedStatus(Byte value) {
        set(20, value);
    }

    /**
     * Getter for <code>tweetsenser.status.retweeted_status</code>.
     */
    public Byte getRetweetedStatus() {
        return (Byte) get(20);
    }

    /**
     * Setter for <code>tweetsenser.status.hashtag_entities</code>.
     */
    public void setHashtagEntities(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>tweetsenser.status.hashtag_entities</code>.
     */
    public String getHashtagEntities() {
        return (String) get(21);
    }

    /**
     * Setter for <code>tweetsenser.status.current_user_retweet_id</code>.
     */
    public void setCurrentUserRetweetId(Integer value) {
        set(22, value);
    }

    /**
     * Getter for <code>tweetsenser.status.current_user_retweet_id</code>.
     */
    public Integer getCurrentUserRetweetId() {
        return (Integer) get(22);
    }

    /**
     * Setter for <code>tweetsenser.status.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(23, value);
    }

    /**
     * Getter for <code>tweetsenser.status.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(23);
    }

    /**
     * Setter for <code>tweetsenser.status.user_name</code>.
     */
    public void setUserName(String value) {
        set(24, value);
    }

    /**
     * Getter for <code>tweetsenser.status.user_name</code>.
     */
    public String getUserName() {
        return (String) get(24);
    }

    /**
     * Setter for <code>tweetsenser.status.screen_name</code>.
     */
    public void setScreenName(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>tweetsenser.status.screen_name</code>.
     */
    public String getScreenName() {
        return (String) get(25);
    }

    /**
     * Setter for <code>tweetsenser.status.user_location</code>.
     */
    public void setUserLocation(String value) {
        set(26, value);
    }

    /**
     * Getter for <code>tweetsenser.status.user_location</code>.
     */
    public String getUserLocation() {
        return (String) get(26);
    }

    /**
     * Setter for <code>tweetsenser.status.user_description</code>.
     */
    public void setUserDescription(String value) {
        set(27, value);
    }

    /**
     * Getter for <code>tweetsenser.status.user_description</code>.
     */
    public String getUserDescription() {
        return (String) get(27);
    }

    /**
     * Setter for <code>tweetsenser.status.is_contributors_enabled</code>.
     */
    public void setIsContributorsEnabled(Byte value) {
        set(28, value);
    }

    /**
     * Getter for <code>tweetsenser.status.is_contributors_enabled</code>.
     */
    public Byte getIsContributorsEnabled() {
        return (Byte) get(28);
    }

    /**
     * Setter for <code>tweetsenser.status.profile_image_url</code>.
     */
    public void setProfileImageUrl(String value) {
        set(29, value);
    }

    /**
     * Getter for <code>tweetsenser.status.profile_image_url</code>.
     */
    public String getProfileImageUrl() {
        return (String) get(29);
    }

    /**
     * Setter for <code>tweetsenser.status.profile_image_url_http</code>.
     */
    public void setProfileImageUrlHttp(String value) {
        set(30, value);
    }

    /**
     * Getter for <code>tweetsenser.status.profile_image_url_http</code>.
     */
    public String getProfileImageUrlHttp() {
        return (String) get(30);
    }

    /**
     * Setter for <code>tweetsenser.status.url</code>.
     */
    public void setUrl(String value) {
        set(31, value);
    }

    /**
     * Getter for <code>tweetsenser.status.url</code>.
     */
    public String getUrl() {
        return (String) get(31);
    }

    /**
     * Setter for <code>tweetsenser.status.is_protected</code>.
     */
    public void setIsProtected(Byte value) {
        set(32, value);
    }

    /**
     * Getter for <code>tweetsenser.status.is_protected</code>.
     */
    public Byte getIsProtected() {
        return (Byte) get(32);
    }

    /**
     * Setter for <code>tweetsenser.status.followers_count</code>.
     */
    public void setFollowersCount(Integer value) {
        set(33, value);
    }

    /**
     * Getter for <code>tweetsenser.status.followers_count</code>.
     */
    public Integer getFollowersCount() {
        return (Integer) get(33);
    }

    /**
     * Setter for <code>tweetsenser.status.twitter_status</code>.
     */
    public void setTwitterStatus(Byte value) {
        set(34, value);
    }

    /**
     * Getter for <code>tweetsenser.status.twitter_status</code>.
     */
    public Byte getTwitterStatus() {
        return (Byte) get(34);
    }

    /**
     * Setter for <code>tweetsenser.status.profile_use_background_image</code>.
     */
    public void setProfileUseBackgroundImage(Byte value) {
        set(35, value);
    }

    /**
     * Getter for <code>tweetsenser.status.profile_use_background_image</code>.
     */
    public Byte getProfileUseBackgroundImage() {
        return (Byte) get(35);
    }

    /**
     * Setter for <code>tweetsenser.status.friends_count</code>.
     */
    public void setFriendsCount(Integer value) {
        set(36, value);
    }

    /**
     * Getter for <code>tweetsenser.status.friends_count</code>.
     */
    public Integer getFriendsCount() {
        return (Integer) get(36);
    }

    /**
     * Setter for <code>tweetsenser.status.created_at</code>.
     */
    public void setCreatedAt(Date value) {
        set(37, value);
    }

    /**
     * Getter for <code>tweetsenser.status.created_at</code>.
     */
    public Date getCreatedAt() {
        return (Date) get(37);
    }

    /**
     * Setter for <code>tweetsenser.status.favourites_count</code>.
     */
    public void setFavouritesCount(Integer value) {
        set(38, value);
    }

    /**
     * Getter for <code>tweetsenser.status.favourites_count</code>.
     */
    public Integer getFavouritesCount() {
        return (Integer) get(38);
    }

    /**
     * Setter for <code>tweetsenser.status.utc_offset</code>.
     */
    public void setUtcOffset(Integer value) {
        set(39, value);
    }

    /**
     * Getter for <code>tweetsenser.status.utc_offset</code>.
     */
    public Integer getUtcOffset() {
        return (Integer) get(39);
    }

    /**
     * Setter for <code>tweetsenser.status.time_zone</code>.
     */
    public void setTimeZone(String value) {
        set(40, value);
    }

    /**
     * Getter for <code>tweetsenser.status.time_zone</code>.
     */
    public String getTimeZone() {
        return (String) get(40);
    }

    /**
     * Setter for <code>tweetsenser.status.statuses_count</code>.
     */
    public void setStatusesCount(Integer value) {
        set(41, value);
    }

    /**
     * Getter for <code>tweetsenser.status.statuses_count</code>.
     */
    public Integer getStatusesCount() {
        return (Integer) get(41);
    }

    /**
     * Setter for <code>tweetsenser.status.is_geo_enabled</code>.
     */
    public void setIsGeoEnabled(Byte value) {
        set(42, value);
    }

    /**
     * Getter for <code>tweetsenser.status.is_geo_enabled</code>.
     */
    public Byte getIsGeoEnabled() {
        return (Byte) get(42);
    }

    /**
     * Setter for <code>tweetsenser.status.is_verified</code>.
     */
    public void setIsVerified(Byte value) {
        set(43, value);
    }

    /**
     * Getter for <code>tweetsenser.status.is_verified</code>.
     */
    public Byte getIsVerified() {
        return (Byte) get(43);
    }

    /**
     * Setter for <code>tweetsenser.status.translator</code>.
     */
    public void setTranslator(Byte value) {
        set(44, value);
    }

    /**
     * Getter for <code>tweetsenser.status.translator</code>.
     */
    public Byte getTranslator() {
        return (Byte) get(44);
    }

    /**
     * Setter for <code>tweetsenser.status.listed_count</code>.
     */
    public void setListedCount(Integer value) {
        set(45, value);
    }

    /**
     * Getter for <code>tweetsenser.status.listed_count</code>.
     */
    public Integer getListedCount() {
        return (Integer) get(45);
    }

    /**
     * Setter for <code>tweetsenser.status.is_follow_request_sent</code>.
     */
    public void setIsFollowRequestSent(Byte value) {
        set(46, value);
    }

    /**
     * Getter for <code>tweetsenser.status.is_follow_request_sent</code>.
     */
    public Byte getIsFollowRequestSent() {
        return (Byte) get(46);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatusRecord
     */
    public StatusRecord() {
        super(Status.STATUS);
    }

    /**
     * Create a detached, initialised StatusRecord
     */
    public StatusRecord(Integer id, Integer tweetId, String product, String subProduct, Timestamp tweetDate, String tweetmsg, String tweetsource, Byte isTruncated, Integer inReplyToStatusId, Integer inReplyToUserId, Byte isFavorited, Byte isRetweeted, Integer favoriteCount, String inReplyToScreenName, String geoLocation, String place, Integer retweetCount, Byte isPossiblySensitive, Byte isoLanguageCode, String lang, Byte retweetedStatus, String hashtagEntities, Integer currentUserRetweetId, Integer userId, String userName, String screenName, String userLocation, String userDescription, Byte isContributorsEnabled, String profileImageUrl, String profileImageUrlHttp, String url, Byte isProtected, Integer followersCount, Byte twitterStatus, Byte profileUseBackgroundImage, Integer friendsCount, Date createdAt, Integer favouritesCount, Integer utcOffset, String timeZone, Integer statusesCount, Byte isGeoEnabled, Byte isVerified, Byte translator, Integer listedCount, Byte isFollowRequestSent) {
        super(Status.STATUS);

        set(0, id);
        set(1, tweetId);
        set(2, product);
        set(3, subProduct);
        set(4, tweetDate);
        set(5, tweetmsg);
        set(6, tweetsource);
        set(7, isTruncated);
        set(8, inReplyToStatusId);
        set(9, inReplyToUserId);
        set(10, isFavorited);
        set(11, isRetweeted);
        set(12, favoriteCount);
        set(13, inReplyToScreenName);
        set(14, geoLocation);
        set(15, place);
        set(16, retweetCount);
        set(17, isPossiblySensitive);
        set(18, isoLanguageCode);
        set(19, lang);
        set(20, retweetedStatus);
        set(21, hashtagEntities);
        set(22, currentUserRetweetId);
        set(23, userId);
        set(24, userName);
        set(25, screenName);
        set(26, userLocation);
        set(27, userDescription);
        set(28, isContributorsEnabled);
        set(29, profileImageUrl);
        set(30, profileImageUrlHttp);
        set(31, url);
        set(32, isProtected);
        set(33, followersCount);
        set(34, twitterStatus);
        set(35, profileUseBackgroundImage);
        set(36, friendsCount);
        set(37, createdAt);
        set(38, favouritesCount);
        set(39, utcOffset);
        set(40, timeZone);
        set(41, statusesCount);
        set(42, isGeoEnabled);
        set(43, isVerified);
        set(44, translator);
        set(45, listedCount);
        set(46, isFollowRequestSent);
    }
}
