/*
 * This file is generated by jOOQ.
*/
package db;


import db.tables.Status;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in tweetsenser
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>tweetsenser.status</code>.
     */
    public static final Status STATUS = db.tables.Status.STATUS;
}
