/*
 * This file is generated by jOOQ.
*/
package db;


import db.tables.Status;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tweetsenser extends SchemaImpl {

    private static final long serialVersionUID = 1964288609;

    /**
     * The reference instance of <code>tweetsenser</code>
     */
    public static final Tweetsenser TWEETSENSER = new Tweetsenser();

    /**
     * The table <code>tweetsenser.status</code>.
     */
    public final Status STATUS = db.tables.Status.STATUS;

    /**
     * No further instances allowed
     */
    private Tweetsenser() {
        super("tweetsenser", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Status.STATUS);
    }
}
